/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clil.xml;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.StringReader;
import java.io.StringWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

/**
 *
 * @author SSLAVIERO
 */
public class EverNote extends javax.swing.JFrame {

    /**
     * Creates new form EverNote
     */
    
Unmarshaller u;

    public EverNote() {
        initComponents();
        JAXBContext jc;

        
        try {
            jc = JAXBContext.newInstance(serverclil.xml.NoteBook.class);
             u= jc.createUnmarshaller();
        } catch (JAXBException ex) {
            Logger.getLogger(EverNote.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Aggiungi nota...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Ricerca per...");

        jMenuItem1.setText("Data...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Descrizione...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //INSERIMENTO NOTA SUL SERVER
        
            Note nota=new Note(jTextField1.getText());

            JAXBContext jb;
        try {        
            jb = JAXBContext.newInstance(Note.class);
            Marshaller m1=jb.createMarshaller();

            try {
            ltclient = new Socket(ip,9090);
            PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(ltclient.getOutputStream())), true);
            StringWriter sw = new StringWriter();
            m1.marshal(nota,sw);
            sw.append("#1");
            out.println(sw.toString());
            
            
            
            
            ltclient.close();  
            
        } catch (IOException ex) {
            Logger.getLogger(EverNote.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        } catch (JAXBException ex) {
            Logger.getLogger(EverNote.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //RICERCA PER DATA
        try {
            
            ltclient = new Socket(ip,9090);
            PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(ltclient.getOutputStream())), true);
            jDialog2 d2=new jDialog2(this,true);
            d2.setVisible(true);
            out.append(d2.date());
            out.append("#3");
            
            out.println();
            
            
            list1.removeAll();
            BufferedReader input = new BufferedReader(new InputStreamReader(ltclient.getInputStream()));
            String risposta = input.readLine();
            
            StringReader reader = new StringReader(risposta);
            
            System.out.println(risposta);
            serverclil.xml.NoteBook o=new serverclil.xml.NoteBook();
            try {
                o = (serverclil.xml.NoteBook) u.unmarshal(reader);

            } catch (JAXBException ex) {
                Logger.getLogger(EverNote.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            for(serverclil.xml.Note nota:o.getNotes())
            {
                list1.add(nota.getDescription()+"   "+nota.getData().toString());
            }
            
        } catch (IOException ex) {
           Logger.getLogger(EverNote.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //RICERCA PER DESCRIZIONE
        try {
            
            ltclient = new Socket(ip,9090);
            PrintWriter out = new PrintWriter(new BufferedWriter(new OutputStreamWriter(ltclient.getOutputStream())), true);
            jDialog1 d=new jDialog1(this,true);
            d.setVisible(true);
            out.append(d.descr());
            out.append("#2");
            
            out.println();
            
            
            
           
            list1.removeAll();
            BufferedReader input = new BufferedReader(new InputStreamReader(ltclient.getInputStream()));
            String risposta = input.readLine();
            
            StringReader reader = new StringReader(risposta);
            
            System.out.println(risposta);
            serverclil.xml.NoteBook o=new serverclil.xml.NoteBook();
            try {
                o = (serverclil.xml.NoteBook) u.unmarshal(reader);

            } catch (JAXBException ex) {
                Logger.getLogger(EverNote.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            for(serverclil.xml.Note nota:o.getNotes())
            {
                list1.add(nota.getDescription()+"    "+nota.getData().toString());
            }
            
            
            
        } catch (IOException ex) {
           Logger.getLogger(EverNote.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EverNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EverNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EverNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EverNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EverNote().setVisible(true);
            }
        });
    }
    Note Note;
    String ip="127.0.0.1";
    Socket ltclient;
    ServerSocket latoServer;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
